-- =====================================================
-- REFERRAL MANAGEMENT TABLES
-- =====================================================

-- Referral codes table (generated by owners for customers)
CREATE TABLE IF NOT EXISTS public.referral_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  member_id UUID REFERENCES public.members(id) ON DELETE SET NULL,
  code TEXT UNIQUE NOT NULL,
  discount_percent NUMERIC DEFAULT 5,
  max_uses INTEGER DEFAULT 10,
  uses_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Referral usage tracking
CREATE TABLE IF NOT EXISTS public.referral_uses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  referral_code_id UUID NOT NULL REFERENCES public.referral_codes(id) ON DELETE CASCADE,
  referrer_member_id UUID REFERENCES public.members(id) ON DELETE SET NULL,
  referred_member_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  discount_applied NUMERIC DEFAULT 0,
  used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_uses ENABLE ROW LEVEL SECURITY;

-- RLS Policies for referral_codes
DROP POLICY IF EXISTS "Owners can manage own referral codes" ON public.referral_codes;
CREATE POLICY "Owners can manage own referral codes" 
ON public.referral_codes FOR ALL 
USING (owner_id = auth.uid());

-- RLS Policies for referral_uses
DROP POLICY IF EXISTS "Owners can view own referral uses" ON public.referral_uses;
CREATE POLICY "Owners can view own referral uses" 
ON public.referral_uses FOR ALL 
USING (owner_id = auth.uid());

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_referral_codes_owner ON public.referral_codes(owner_id);
CREATE INDEX IF NOT EXISTS idx_referral_codes_member ON public.referral_codes(member_id);
CREATE INDEX IF NOT EXISTS idx_referral_codes_code ON public.referral_codes(code);
CREATE INDEX IF NOT EXISTS idx_referral_uses_owner ON public.referral_uses(owner_id);
CREATE INDEX IF NOT EXISTS idx_referral_uses_code ON public.referral_uses(referral_code_id);
